version: '3.8'

services:
  # ===========================================
  # PostgreSQL Database
  # ===========================================
  db:
    image: docker.io/library/postgres:15-alpine
    container_name: saas_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-odoo_secret_2024}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - postgres_data:/var/lib/postgresql/data/pgdata
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-odoo} -d ${POSTGRES_DB:-postgres}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - saas_network

  # ===========================================
  # Redis Cache & Queue
  # ===========================================
  redis:
    image: docker.io/library/redis:7-alpine
    container_name: saas_redis
    restart: unless-stopped
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    ports:
      - "${REDIS_PORT:-6379}:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 5s
    networks:
      - saas_network

  # ===========================================
  # Odoo ERP Service
  # ===========================================
  odoo:
    build:
      context: ./odoo
      dockerfile: Dockerfile
    container_name: saas_odoo
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    environment:
      HOST: db
      PORT: 5432
      USER: ${POSTGRES_USER:-odoo}
      PASSWORD: ${POSTGRES_PASSWORD:-odoo_secret_2024}
      ODOO_ADMIN_PASSWD: ${ODOO_MASTER_PASSWORD:-admin_master_2024}
    volumes:
      - odoo_data:/var/lib/odoo
      - odoo_addons:/mnt/extra-addons
      - ./odoo/odoo.conf:/etc/odoo/odoo.conf:ro
    ports:
      - "${ODOO_PORT:-8069}:8069"
      - "${ODOO_LONGPOLLING_PORT:-8072}:8072"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8069/web/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s
    networks:
      - saas_network

  # ===========================================
  # Admin Dashboard (Flask)
  # ===========================================
  admin:
    build:
      context: ./admin
      dockerfile: Dockerfile
    container_name: saas_admin
    restart: unless-stopped
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
      odoo:
        condition: service_healthy
    environment:
      FLASK_APP: app.py
      FLASK_ENV: ${FLASK_ENV:-development}
      FLASK_DEBUG: ${FLASK_DEBUG:-1}
      SECRET_KEY: ${SECRET_KEY:-dev_secret_key_change_in_production}
      # Database
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_USER: ${POSTGRES_USER:-odoo}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-odoo_secret_2024}
      POSTGRES_DB: ${POSTGRES_DB:-postgres}
      # Redis
      REDIS_HOST: redis
      REDIS_PORT: 6379
      # Odoo
      ODOO_HOST: odoo
      ODOO_PORT: 8069
      ODOO_MASTER_PASSWORD: ${ODOO_MASTER_PASSWORD:-admin_master_2024}
    ports:
      - "${ADMIN_PORT:-5000}:5000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s
    networks:
      - saas_network

networks:
  saas_network:
    driver: bridge

volumes:
  postgres_data:
  redis_data:
  odoo_data:
  odoo_addons:
